
* tasks
*** TODO Check that git is installed                           :elisp:nisp:
    Elisp needs to verify that git is actually there.
*** DONE Install emacs-goodies-el
    Needed for htmlize.el

*** TODO Gitsum needs git-status
    Can't seem to split a diff without it.

*** TODO Define different keys for Console and X :keymap:elisp:
    The problem is super, hyper and alt are not usable in a console.
    [[file:my/my-keymap.el]]

*** BUG (nisp-reload-site-file) Does not refresh system paths
    When I wrote this, it was intended to reload system paths so that
    installing new things in debian did not force me to restart emacs.

*** TODO add customize option to add arbitrary extension       :nisp_paste:
    <nixeagle> charlie:   [06:13]
<nixeagle> # DefaultType: the default MIME type the server will use for a
           document
<nixeagle> # if it cannot otherwise determine one, such as from filename
           extensions.
<nixeagle> # If your server contains mostly text or HTML documents, "text/plain"
           is
<nixeagle> # a good value.  If most of your content is binary, such as
           applications
<nixeagle> # or images, you may want to use "application/octet-stream" instead
           to
<nixeagle> # keep browsers from trying to display binary files as though they
           are
<nixeagle> # text.
<nixeagle> DefaultType text/plain
<nixeagle> charlie: found it, I have mod_magic installed  [06:15]
<nixeagle> so apache serves the right type from hints in the file
<nixeagle> set the DefaultType in your access file or your vhost: text/html


* Worth my while

*** How to setup emacs + screen
    http://www.emacswiki.org/emacs/GnuScreen


*** Multi user screen
    http://aperiodic.net/screen/multiuser



* Debian
*** Packages to think about installing
    - [ ] buildbot
    - [ ] debram
    - [ ] debtree
    - [ ] faketime



*** Neat packages installed, check them out
    - [ ] devscripts-el
    - [ ] fakeroot-ng
    - [ ] pbuilder - create and maintain chroot environment
    - [ ] lintian - lint for .deb
    - [ ] dhelp - search debian documentation locally.
    - [ ] elib - helper for elisp programs.
    - [ ] dbtoepub - converter thingie to ebook

*** suggested installed, check out
    - [ ] catdvi
    - [ ] bison
    - [ ] debconf-utils
    - [ ] flex
    - [ ] gnuplot
    - [ ] ri - commandline way to ask about ruby funcs and such
    - [ ] iso-codes

*** Emacs stuff to think about
  - [ ] bbdb
  - [ ] apel
  - [ ] auctex
  - [ ] cmucl-source
  - [ ] colordiff - color diff output
  - [ ] darcsum
  - [ ] devhelp - help with dev stuff, supposed to have emacs
    integration
  - [ ] docbook2x

***** Dictonary stuff
  - [ ] dictem
  - [ ] dictionary-el

* Sid
  - [ ] tagcoll - analyze tag collections.
